language: go
sudo: required

go:
  - "1.15"

services:
  - docker
  - postgresql
  - redis

addons:
  postgresql: "12"
  apt:
    packages:
    - postgresql-12
    - postgresql-client-12
env:
  global:
  - PGVER=12
  - PGPORT=5433

before_script:
  - sudo sed -i -e '/local.*peer/s/postgres/all/' -e 's/peer\|md5/trust/g' /etc/postgresql/*/main/pg_hba.conf
  - sudo systemctl restart postgresql@12-main
  - sleep 1
  - psql -c "CREATE DATABASE cybertect;" -U postgres
  - psql -c "CREATE USER vicanso WITH PASSWORD 'A123456';" -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON DATABASE cybertect to vicanso;" -U postgres

script:
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin latest
  - make lint
  - GO_ENV=test make test

after_success:
  - docker build -t cybertect .
  - docker tag cybertect $DOCKER_USERNAME/cybertect:latest
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push $DOCKER_USERNAME/cybertect:latest
  - docker images
